default: &default
  secret_key_base: 71177853f4f9cf4d8a9e350280051ca55bb37d8b624ba9c3368345576dc2d06e2d58d208a9d8027ae0712820ff8650da161b3f72d6dd9ee191459537997a3a54
  redis_url: redis://localhost:6379/stocks

test:
  <<: *default
  database_url: postgres://postgres@localhost:5432/stocks_test

development:
  <<: *default
  database_url: postgres://postgres@localhost:5432/stocks_development

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  sidekiq_username: andey
  sidekiq_password: diablo